export const datas = [
  {
    first: "Saige",
    last: "Robel",
    email: "Saige.Robel@perry.biz",
    address: "2873 Jast Rest",
    created: "September 26, 2013",
    balance: "$1,622.30",
    profileImg: "https://randomuser.me/api/portraits/women/33.jpg",
  },
  {
    first: "Francesca",
    last: "Spencer",
    email: "mintgreenturtle24@gmail.com",
    address: "762 Caitlyn Crescent",
    created: "May 15, 2013",
    balance: "$5,042.46",
    profileImg: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    first: "Araceli",
    last: "Mertz",
    email: "yellowturtle81@gmail.com",
    address: "9191 Kohler Radial",
    created: "April 6, 2017",
    balance: "$9,268.43",
    profileImg: "https://randomuser.me/api/portraits/women/79.jpg",
  },
  {
    first: "Giles",
    last: "Cronin",
    email: "Giles.Cronin@jada.net",
    address: "2028 Marisa Oval",
    created: "June 30, 2014",
    balance: "$9,312.14",
    profileImg: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    first: "Aleen",
    last: "Gutkowski",
    email: "violetsquirrel76@gmail.com",
    address: "549 Schmitt Plain",
    created: "June 27, 2020",
    balance: "$3,584.25",
    profileImg: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    first: "Francis",
    last: "Russel",
    email: "whitegiraffe95@gmail.com",
    address: "77268 Hagenes Point",
    created: "June 21, 2019",
    balance: "$3,955.06",
    profileImg: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    first: "Jess",
    last: "Olson",
    email: "skybluesquirrel39@gmail.com",
    address: "5439 Murray Fall",
    created: "December 1, 2017",
    balance: "$742.42",
    profileImg: "https://randomuser.me/api/portraits/men/90.jpg",
  },
  {
    first: "Aubree",
    last: "Bergstrom",
    email: "violetrabbit85@gmail.com",
    address: "0188 McClure Place",
    created: "December 22, 2014",
    balance: "$6,538.90",
    profileImg: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    first: "Dillon",
    last: "Weimann",
    email: "Dillon.Weimann@jewell.info",
    address: "26942 Bogan Grove",
    created: "February 19, 2021",
    balance: "$6,132.98",
    profileImg: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    first: "Lola",
    last: "Gibson",
    email: "Lola.Gibson@deangelo.biz",
    address: "33619 Wisoky Forges",
    created: "August 14, 2013",
    balance: "$1,576.44",
    profileImg: "https://randomuser.me/api/portraits/men/81.jpg",
  },
  {
    first: "Keenan",
    last: "Pfeffer",
    email: "azuregiraffe78@gmail.com",
    address: "9770 Melody Stream",
    created: "May 20, 2020",
    balance: "$7,717.19",
    profileImg: "https://randomuser.me/api/portraits/men/23.jpg",
  },
  {
    first: "Bill",
    last: "Volkman",
    email: "Bill.Volkman@megane.name",
    address: "6819 Smitham Oval",
    created: "March 3, 2019",
    balance: "$4,418.01",
    profileImg: "https://randomuser.me/api/portraits/men/78.jpg",
  },
  {
    first: "Claudia",
    last: "Hickle",
    email: "maroonrabbit00@gmail.com",
    address: "08524 Lesch Inlet",
    created: "October 4, 2015",
    balance: "$8,385.53",
    profileImg: "https://randomuser.me/api/portraits/men/49.jpg",
  },
  {
    first: "Junior",
    last: "Harvey",
    email: "Junior.Harvey@otilia.com",
    address: "344 Juwan Points",
    created: "August 10, 2014",
    balance: "$5,942.96",
    profileImg: "https://randomuser.me/api/portraits/men/60.jpg",
  },
  {
    first: "Ewald",
    last: "Barton",
    email: "redwolf72@gmail.com",
    address: "497 McKenzie Flat",
    created: "November 29, 2015",
    balance: "$6,346.32",
    profileImg: "https://randomuser.me/api/portraits/women/32.jpg",
  },
  {
    first: "Heath",
    last: "Krajcik",
    email: "limewolf57@gmail.com",
    address: "080 Jewel Pines",
    created: "June 2, 2014",
    balance: "$5,010.17",
    profileImg: "https://randomuser.me/api/portraits/men/75.jpg",
  },
  {
    first: "Sasha",
    last: "Denesik",
    email: "Sasha.Denesik@horace.org",
    address: "896 Dibbert Springs",
    created: "August 29, 2017",
    balance: "$7,780.64",
    profileImg: "https://randomuser.me/api/portraits/men/51.jpg",
  },
  {
    first: "Arvid",
    last: "Grady",
    email: "tealsquirrel61@gmail.com",
    address: "7223 Kihn Stravenue",
    created: "September 11, 2022",
    balance: "$3,045.58",
    profileImg: "https://randomuser.me/api/portraits/women/60.jpg",
  },
  {
    first: "Lisette",
    last: "Jakubowski",
    email: "Lisette.Jakubowski@simone.biz",
    address: "297 Minerva Views",
    created: "April 16, 2015",
    balance: "$2,075.55",
    profileImg: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    first: "Fausto",
    last: "Ledner",
    email: "Fausto.Ledner@carey.net",
    address: "993 Connelly Burgs",
    created: "June 2, 2019",
    balance: "$7,549.31",
    profileImg: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    first: "Mike",
    last: "Mills",
    email: "salmongiraffe24@gmail.com",
    address: "6554 Sarai Roads",
    created: "January 26, 2020",
    balance: "$6,692.65",
    profileImg: "https://randomuser.me/api/portraits/men/71.jpg",
  },
  {
    first: "Eda",
    last: "Abernathy",
    email: "mintgreenfrog02@gmail.com",
    address: "12079 Giovani Drives",
    created: "September 1, 2022",
    balance: "$1,325.69",
    profileImg: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    first: "Madge",
    last: "Becker",
    email: "greysquirrel11@gmail.com",
    address: "1786 Crooks Pines",
    created: "April 7, 2014",
    balance: "$2,424.28",
    profileImg: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    first: "Rozella",
    last: "O'Keefe",
    email: "indigofrog98@gmail.com",
    address: "73066 Destin Drive",
    created: "April 9, 2014",
    balance: "$5,945.99",
    profileImg: "https://randomuser.me/api/portraits/women/53.jpg",
  },
  {
    first: "Damaris",
    last: "Hayes",
    email: "limewolf75@gmail.com",
    address: "026 Kertzmann Lights",
    created: "June 22, 2015",
    balance: "$2,070.00",
    profileImg: "https://randomuser.me/api/portraits/men/67.jpg",
  },
  {
    first: "Lawrence",
    last: "Armstrong",
    email: "Lawrence.Armstrong@ricardo.biz",
    address: "8455 Kirlin Mount",
    created: "March 24, 2020",
    balance: "$7,139.68",
    profileImg: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    first: "Tyler",
    last: "Klein",
    email: "Tyler.Klein@cyril.org",
    address: "209 Doris Plains",
    created: "October 14, 2016",
    balance: "$4,297.54",
    profileImg: "https://randomuser.me/api/portraits/men/79.jpg",
  },
];
